"""empty message

Revision ID: 836702d7fd6e
Revises: 
Create Date: 2022-09-17 11:46:16.319665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836702d7fd6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_path', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('titulo', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=80), nullable=False),
    sa.Column('upload', sa.String(length=80), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('area', sa.String(length=80), nullable=False),
    sa.Column('ano', sa.String(length=80), nullable=False),
    sa.Column('autores', sa.String(length=80), nullable=False),
    sa.Column('tags', sa.String(length=80), nullable=False),
    sa.Column('premiacao', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('senha_hash', sa.LargeBinary(length=128), nullable=True),
    sa.Column('role_user', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('senha_hash', sa.LargeBinary(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_administrador_email'), 'administrador', ['email'], unique=True)
    op.create_table('arquivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_comum',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('senha_hash', sa.LargeBinary(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_usuario_comum_email'), 'usuario_comum', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_comum_email'), table_name='usuario_comum')
    op.drop_table('usuario_comum')
    op.drop_table('arquivo')
    op.drop_index(op.f('ix_administrador_email'), table_name='administrador')
    op.drop_table('administrador')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('file')
    # ### end Alembic commands ###
